export const REGISTER_BASIC = "REGISTER_BASIC";
export const REGISTER_GOOGLE = "REGISTER_GOOGLE";
export const LOGIN_REGISTER = "LOGIN_REGISTER";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const UPDATE_CART_FROM_LOCAL_STORAGE = "UPDATE_CART_FROM_LOCAL_STORAG";